plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "db/queue_schema.rb"

Style/Documentation:
  Enabled: false
