plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "db/queue_schema.rb"
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"
